/*
 * File      : parallel.test.js
 * Layer     : test
 * Caller    : npm test
 * Calls     : node:test, node:assert/strict, node:child_process, node:fs, node:path
 *
 * Variables : __dirname, root, PREVIEW_OUTPUTS, LIB_OUTPUTS
 * Operations: (test cases)
 *             _cleanPreview (private)
 *             _cleanLib     (private)
 * Exports   : (none)
 */

// === IMPORTS ===

import { test } from 'node:test';
import { vessert as assert } from './vessert.js';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// === VARIABLES ===

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

/**
 * Expected artifacts generated by the preview pipeline.
 * @type {string[]}
 */
const PREVIEW_OUTPUTS = [
  'index.html',
  'style.css',
  'search.js',
  'demo/hello-world.html',
  'demo/release-1-0.html',
  'demo/halo-dunia.html',
  'demo/deep-dive-rendering.html',
  'demo/theme-dark.html'
];

/**
 * Expected artifacts generated by the library pipeline.
 * @type {string[]}
 */
const LIB_OUTPUTS = [
  'dist/pupputer.js',
  'dist/pupputer.cjs',
  'dist/pupputer.min.js',
  'dist/index.d.ts'
];

// === PRIVATE METHODS ===

/**
 * Clean all preview build artifacts.
 * @returns {void}
 */
function _cleanPreview() {
  fs.rmSync(path.join(root, 'demo'), { recursive: true, force: true });
  fs.rmSync(path.join(root, 'index.html'), { force: true });
  fs.rmSync(path.join(root, 'style.css'), { force: true });
  fs.rmSync(path.join(root, 'search.js'), { force: true });
}

/**
 * Clean all library build artifacts.
 * @returns {void}
 */
function _cleanLib() {
  fs.rmSync(path.join(root, 'dist'), { recursive: true, force: true });
}

// === TESTS ===

test('preview pipeline writes only to demo/ and root assets, never touching dist/', () => {
  _cleanPreview();
  _cleanLib();

  execSync('node scripts/build-preview.js', { cwd: root, stdio: 'pipe' });

  for (const file of PREVIEW_OUTPUTS) {
    assert.ok(fs.existsSync(path.join(root, file)), `Expected preview artifact: ${file}`);
  }

  assert.ok(!fs.existsSync(path.join(root, 'dist')), 'Preview pipeline must never create or touch dist/');
});

test('library pipeline writes only to dist/, never touching demo/ or root preview assets', () => {
  _cleanPreview();
  _cleanLib();

  execSync('node scripts/build-lib.js', { cwd: root, stdio: 'pipe' });

  for (const file of LIB_OUTPUTS) {
    assert.ok(fs.existsSync(path.join(root, file)), `Expected library artifact: ${file}`);
  }

  assert.ok(!fs.existsSync(path.join(root, 'demo')), 'Library pipeline must never create or touch demo/');
  assert.ok(!fs.existsSync(path.join(root, 'index.html')), 'Library pipeline must never create or touch index.html');
});

test('preview pipeline remains fully functional when dist/ is completely absent or corrupted', () => {
  _cleanLib();
  // Create an invalid/corrupted dummy file in dist to simulate a broken library build
  const distDir = path.join(root, 'dist');
  fs.mkdirSync(distDir, { recursive: true });
  fs.writeFileSync(path.join(distDir, 'broken.invalid'), 'CORRUPTED');

  // Preview build must succeed and read from src/ through Pupputer.js shim
  assert.doesNotThrow(() => {
    execSync('node scripts/build-preview.js', { cwd: root, stdio: 'pipe' });
  });

  assert.ok(fs.existsSync(path.join(root, 'index.html')), 'Preview index.html exists despite dist state');
});

test('library build and exports remain fully functional when demo/ is deleted', () => {
  _cleanPreview();

  assert.doesNotThrow(() => {
    execSync('node scripts/build-lib.js', { cwd: root, stdio: 'pipe' });
  });

  assert.ok(fs.existsSync(path.join(root, 'dist/pupputer.js')), 'dist/pupputer.js produced cleanly');
});

test('parallel execution of both pipelines completes without collision', () => {
  _cleanPreview();
  _cleanLib();

  // Run preview and library builds
  execSync('node scripts/build-preview.js', { cwd: root, stdio: 'pipe' });
  execSync('node scripts/build-lib.js', { cwd: root, stdio: 'pipe' });

  for (const file of PREVIEW_OUTPUTS) {
    assert.ok(fs.existsSync(path.join(root, file)), `Preview artifact intact: ${file}`);
  }

  for (const file of LIB_OUTPUTS) {
    assert.ok(fs.existsSync(path.join(root, file)), `Library artifact intact: ${file}`);
  }
});

// === EXPORTS ===

export {};
